const data = {
  products: [
    {
      name: 'Ralph Lauren Cable-Knit Jumper',
      slug: 'rl-ck-jumper',
      category: 'Sweaters & Jumpers',
      image: '/images/prod1.jpeg',
      price: 800,
      countInStock: 10,
      brand: 'Ralph Lauren',
      rating: 4.5,
      numReviews: 10,
      description: 'Iconic Cable knit weave featured in this Jumper',
    },
    {
      name: 'Ralph Lauren Crew-Neck Jumper',
      slug: 'rl-cn-jumper',
      category: 'Sweaters & Jumpers',
      image: '/images/prod2.jpeg',
      price: 700,
      countInStock: 10,
      brand: 'Ralph Lauren',
      rating: 4.5,
      numReviews: 10,
      description: 'Bright Pink, and soft',
    },
    {
      name: 'Zara White Linen Shirt',
      slug: 'zara-wl-shirt',
      category: 'Shirts',
      image: '/images/prod3.jpeg',
      price: 400,
      countInStock: 10,
      brand: 'Zara',
      rating: 4.5,
      numReviews: 10,
      description: 'You can never go wrong with clean look',
    },
    {
      name: 'Zara Blue Blazer',
      slug: 'zara-bu-blazer',
      category: 'Blazers',
      image: '/images/p4.jpeg',
      price: 1700,
      countInStock: 10,
      brand: 'Zara',
      rating: 4.5,
      numReviews: 10,
      description: 'Blue as NIght, smooth as ever',
    },
  ],
};

export default data;
